export const initialDatatables = [
  {
    id: 1,
    instruction:
      "<p>1 modul ini berisikan 110 soal dengan waktu 100 menit kamu butuh strategi pengerjaan yang tepat untuk mendapatkan nilai yang sesuai atau melebihi passing grade.</p><p><b>Cara Mengerjakan</b></p><p><b>Kerjakan terlebih dahulu soal-soal dengan kategori TKP (Tes Karakteristik Pribadi) </b></p><p>Pada kategori ini berjumlah 45 soal dimulai dari no 66 Sampai 110 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 32 soal dengan  waktu yang dimiliki kurang lebih 55 menit</p><p><b><br></b></p><p><b>Lanjut dengan mengerjakan soal-soal dengan kategori TWK (Tes Wawasan Kebangsaan)</b></p><p>Pada kategori ini berjumlah 30 soal  dimulai dari no 1 sampai 30 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 13 soal dengan waktu yang dimiliki kurang lebih 15 menit</p><p><b><br></b></p><p><b>Kemudian kerjakan soal-soal dengan kategori  TIU (Tes Intelegensi Umum)</b></p><p>Pada kategori ini  berjumlah 35 soal dimulai dari no 41 sampai 65 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 16 soal dengan waktu yang kalian miliki 25 menit</p><p><b><br></b></p><p><b>Jawablah semua soal yang belum sempat dijawab</b></p><p>Pada tahap ini kalian cuma memiliki waktu 5 menit yang tersisah gunakan waktu 5 menit ini untuk menjawab soal-soal yang belum dijawab serta koreksi kembali soal-soal yang sudah dijawab</p><p>Untuk soal-soal yang kalian tidak tahu jawabannya kalian bisa menggunakan cara jawab dengan pilihan yang konsisten seperti pilih opsi jawaban B atau C semua. cara langkah ini dilakukan paling akhir jika benar-benar tidak tahu jawabannya.</p><p><br></p><p><b>Selamat Mengerjakan !</b></p>",
    program: "SKD",
  },
  {
    id: 2,
    instruction:
      "<p>1 modul ini berisikan 110 soal dengan waktu 100 menit kamu butuh strategi pengerjaan yang tepat untuk mendapatkan nilai yang sesuai atau melebihi passing grade.</p><p><b>Cara Mengerjakan</b></p><p><b>Kerjakan terlebih dahulu soal-soal dengan kategori TKP (Tes Karakteristik Pribadi) </b></p><p>Pada kategori ini berjumlah 45 soal dimulai dari no 66 Sampai 110 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 32 soal dengan  waktu yang dimiliki kurang lebih 55 menit</p><p><b><br></b></p><p><b>Lanjut dengan mengerjakan soal-soal dengan kategori TWK (Tes Wawasan Kebangsaan)</b></p><p>Pada kategori ini berjumlah 30 soal  dimulai dari no 1 sampai 30 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 13 soal dengan waktu yang dimiliki kurang lebih 15 menit</p><p><b><br></b></p><p><b>Kemudian kerjakan soal-soal dengan kategori  TIU (Tes Intelegensi Umum)</b></p><p>Pada kategori ini  berjumlah 35 soal dimulai dari no 41 sampai 65 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 16 soal dengan waktu yang kalian miliki 25 menit</p><p><b><br></b></p><p><b>Jawablah semua soal yang belum sempat dijawab</b></p><p>Pada tahap ini kalian cuma memiliki waktu 5 menit yang tersisah gunakan waktu 5 menit ini untuk menjawab soal-soal yang belum dijawab serta koreksi kembali soal-soal yang sudah dijawab</p><p>Untuk soal-soal yang kalian tidak tahu jawabannya kalian bisa menggunakan cara jawab dengan pilihan yang konsisten seperti pilih opsi jawaban B atau C semua. cara langkah ini dilakukan paling akhir jika benar-benar tidak tahu jawabannya.</p><p><br></p><p><b>Selamat Mengerjakan !</b></p>",
    program: "SKD",
  },
  {
    id: 3,
    instruction:
      "<p>1 modul ini berisikan 110 soal dengan waktu 100 menit kamu butuh strategi pengerjaan yang tepat untuk mendapatkan nilai yang sesuai atau melebihi passing grade.</p><p><b>Cara Mengerjakan</b></p><p><b>Kerjakan terlebih dahulu soal-soal dengan kategori TKP (Tes Karakteristik Pribadi) </b></p><p>Pada kategori ini berjumlah 45 soal dimulai dari no 66 Sampai 110 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 32 soal dengan  waktu yang dimiliki kurang lebih 55 menit</p><p><b><br></b></p><p><b>Lanjut dengan mengerjakan soal-soal dengan kategori TWK (Tes Wawasan Kebangsaan)</b></p><p>Pada kategori ini berjumlah 30 soal  dimulai dari no 1 sampai 30 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 13 soal dengan waktu yang dimiliki kurang lebih 15 menit</p><p><b><br></b></p><p><b>Kemudian kerjakan soal-soal dengan kategori  TIU (Tes Intelegensi Umum)</b></p><p>Pada kategori ini  berjumlah 35 soal dimulai dari no 41 sampai 65 untuk lulus passing grade kalian harus menjawab soal benar sebanyak 16 soal dengan waktu yang kalian miliki 25 menit</p><p><b><br></b></p><p><b>Jawablah semua soal yang belum sempat dijawab</b></p><p>Pada tahap ini kalian cuma memiliki waktu 5 menit yang tersisah gunakan waktu 5 menit ini untuk menjawab soal-soal yang belum dijawab serta koreksi kembali soal-soal yang sudah dijawab</p><p>Untuk soal-soal yang kalian tidak tahu jawabannya kalian bisa menggunakan cara jawab dengan pilihan yang konsisten seperti pilih opsi jawaban B atau C semua. cara langkah ini dilakukan paling akhir jika benar-benar tidak tahu jawabannya.</p><p><br></p><p><b>Selamat Mengerjakan !</b></p>",
    program: "SKD",
  },
];
