export const initialDatatables = [
  {
    id: 1,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 2,
    product_code: "OL-SKD-123",
    title: "Modul 2",
    modul_name: "SKD-48-2",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 3,
    product_code: "OL-SKD-123",
    title: "Modul 3",
    modul_name: "SKD-48-3",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 4,
    product_code: "OL-SKD-123",
    title: "Modul 4",
    modul_name: "SKD-48-4",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 5,
    product_code: "OL-SKD-123",
    title: "Modul 5",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 6,
    product_code: "OL-SKD-123",
    title: "Modul 6",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 7,
    product_code: "OL-SKD-123",
    title: "Modul 7",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 8,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 9,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 10,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 11,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 12,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 13,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
  {
    id: 14,
    product_code: "OL-SKD-123",
    title: "Modul 1",
    modul_name: "SKD-48-1",
    status: true,
    branch_code: 'KB0002',
    cluster_total: 5,
  },
];
